
import "./globals.css";

import { UserProvider } from "../../context/userContext";

export const metadata = {
  title: "SOLSCAPE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
        {children}
        </UserProvider>
      </body>
    </html>
  );
}
